import streamlit as st
from rag_pipeline import create_rag_chain
from collections import Counter
import os
import json
import requests


def _extract_source_files(source_documents):
    files = []
    for doc in source_documents:
        source_path = doc.metadata.get("source") if doc.metadata else None
        if source_path:
            files.append(source_path)
    return files


def _resolve_llm_identity():
    provider = os.getenv("LLM_PROVIDER", "openai").lower()
    if provider == "azure":
        return os.getenv("AZURE_OPENAI_CHAT_DEPLOYMENT", "unset")
    return os.getenv("LLM_MODEL", "gpt-3.5-turbo")


def _resolve_embedding_identity():
    provider = os.getenv("LLM_PROVIDER", "openai").lower()
    if provider == "azure":
        return os.getenv("AZURE_OPENAI_EMBEDDING_MODEL", "text-embedding-3-small")
    if provider == "ollama":
        return os.getenv("OLLAMA_EMBEDDING_MODEL", "nomic-embed-text")
    return os.getenv("OPENAI_EMBEDDING_MODEL", "text-embedding-3-small")


def _get_int_env(name: str, default: int) -> int:
    value = os.getenv(name)
    if value is None:
        return default
    try:
        return int(value)
    except ValueError:
        return default


def _render_rag_api_panel():
    provider = os.getenv("LLM_PROVIDER", "openai").lower()
    api_host = os.getenv("RAG_API_HOST", "localhost")
    api_port = os.getenv("RAG_API_PORT", "8000")
    api_base_url = f"http://{api_host}:{api_port}"

    runtime = {
        "provider": provider,
        "llm": _resolve_llm_identity(),
        "embedding_model": _resolve_embedding_identity(),
        "retriever_search_type": os.getenv("RAG_RETRIEVER_SEARCH_TYPE", "mmr"),
        "retriever_k": _get_int_env("RAG_RETRIEVER_K", 12),
        "retriever_fetch_k": _get_int_env("RAG_RETRIEVER_FETCH_K", 40),
        "vector_store": "FAISS",
        "index_path": "faiss_index",
        "fastapi_base_url": api_base_url,
    }

    request_contract = {
        "query": "What are the main improvements in GPT-4?"
    }

    response_contract = {
        "result": "Answer generated by the LLM with retrieved context.",
        "source_documents": [
            {
                "metadata": {
                    "source": "data/example.pdf"
                },
                "page_content": "Retrieved chunk text..."
            }
        ]
    }

    with st.expander("RAG API exposed by this app", expanded=False):
        st.write("**FastAPI exposure**")
        st.code(
            "uvicorn openai_compatible_api:app --host 0.0.0.0 --port 8000",
            language="bash",
        )
        st.write("**Base URL:**", api_base_url)
        st.write("**FastAPI endpoints (OpenAI-compatible)**")
        st.code(
            "GET /health\nGET /v1/models\nPOST /v1/chat/completions (supports stream=true)",
            language="text",
        )

        st.write("**Invocation method:** `qa_chain({\"query\": ...})`")
        st.write("**Request contract**")
        st.code(json.dumps(request_contract, indent=2), language="json")
        st.write("**Response contract**")
        st.code(json.dumps(response_contract, indent=2), language="json")
        st.write("**Current runtime configuration**")
        st.json(runtime)


def _get_fastapi_base_url() -> str:
    api_host = os.getenv("RAG_API_HOST", "localhost")
    api_port = os.getenv("RAG_API_PORT", "8000")
    return f"http://{api_host}:{api_port}"


def _query_via_openai_compatible_api(query: str, stream: bool):
    api_base_url = _get_fastapi_base_url()
    payload = {
        "model": os.getenv("LLM_MODEL", "rag-local"),
        "messages": [{"role": "user", "content": query}],
        "stream": stream,
    }

    if not stream:
        response = requests.post(
            f"{api_base_url}/v1/chat/completions",
            json=payload,
            timeout=120,
        )
        response.raise_for_status()
        data = response.json()
        answer = data.get("choices", [{}])[0].get("message", {}).get("content", "")
        sources = data.get("rag_sources", [])
        return answer, sources

    with requests.post(
        f"{api_base_url}/v1/chat/completions",
        json=payload,
        stream=True,
        timeout=180,
    ) as response:
        response.raise_for_status()

        answer = ""
        sources = []
        answer_placeholder = st.empty()

        for raw_line in response.iter_lines(decode_unicode=True):
            if not raw_line:
                continue
            if not raw_line.startswith("data: "):
                continue

            data = raw_line[6:]
            if data == "[DONE]":
                break

            chunk = json.loads(data)
            choices = chunk.get("choices", [])
            if choices:
                delta = choices[0].get("delta", {})
                content_piece = delta.get("content")
                if content_piece:
                    answer += content_piece
                    answer_placeholder.write("**Answer (stream):** " + answer)

            if "rag_sources" in chunk:
                sources = chunk["rag_sources"]

        return answer, sources


def _render_source_file_summary_from_paths(source_paths: list[str]):
    if not source_paths:
        st.caption("No source file metadata found in retrieved documents.")
        return

    file_counts = Counter(source_paths)
    top_source_file, top_count = file_counts.most_common(1)[0]

    st.write("**Main source file used by RAG:**", os.path.basename(top_source_file))
    st.caption(f"Selected in {top_count} retrieved chunk(s)")

    with st.expander("Show retrieved source files"):
        for file_path, count in file_counts.most_common():
            st.write(f"- {os.path.basename(file_path)} ({count} chunk(s))")

st.title("Ask me anything about OpenAI Research")
_render_rag_api_panel()
query = st.text_input("Ask a question...")
mode = st.radio(
    "Execution mode",
    [
        "Direct RAG chain",
        "OpenAI-compatible API (normal)",
        "OpenAI-compatible API (stream)",
    ],
    index=0,
)

if query:
    try:
        if mode == "Direct RAG chain":
            qa_chain = create_rag_chain()
            response = qa_chain({"query": query})
            st.write("**Answer:**", response["result"])

            source_documents = response.get("source_documents", [])
            source_files = _extract_source_files(source_documents)
            _render_source_file_summary_from_paths(source_files)

        elif mode == "OpenAI-compatible API (normal)":
            answer, source_files = _query_via_openai_compatible_api(query=query, stream=False)
            st.write("**Answer (API):**", answer)
            _render_source_file_summary_from_paths(source_files)

        else:
            answer, source_files = _query_via_openai_compatible_api(query=query, stream=True)
            if not answer:
                st.write("**Answer (stream):**")
            _render_source_file_summary_from_paths(source_files)

    except requests.RequestException as exc:
        st.error(
            "FastAPI server is not reachable. Start it with: "
            "uvicorn openai_compatible_api:app --host 0.0.0.0 --port 8000"
        )
        st.caption(str(exc))