import streamlit as st
from rag_pipeline import create_rag_chain
from collections import Counter
import os
import json


def _extract_source_files(source_documents):
    files = []
    for doc in source_documents:
        source_path = doc.metadata.get("source") if doc.metadata else None
        if source_path:
            files.append(source_path)
    return files


def _resolve_llm_identity():
    provider = os.getenv("LLM_PROVIDER", "openai").lower()
    if provider == "azure":
        return os.getenv("AZURE_OPENAI_CHAT_DEPLOYMENT", "unset")
    return os.getenv("LLM_MODEL", "gpt-3.5-turbo")


def _resolve_embedding_identity():
    provider = os.getenv("LLM_PROVIDER", "openai").lower()
    if provider == "azure":
        return os.getenv("AZURE_OPENAI_EMBEDDING_MODEL", "text-embedding-3-small")
    if provider == "ollama":
        return os.getenv("OLLAMA_EMBEDDING_MODEL", "nomic-embed-text")
    return os.getenv("OPENAI_EMBEDDING_MODEL", "text-embedding-3-small")


def _render_rag_api_panel():
    provider = os.getenv("LLM_PROVIDER", "openai").lower()
    api_host = os.getenv("RAG_API_HOST", "localhost")
    api_port = os.getenv("RAG_API_PORT", "8000")
    api_base_url = f"http://{api_host}:{api_port}"

    runtime = {
        "provider": provider,
        "llm": _resolve_llm_identity(),
        "embedding_model": _resolve_embedding_identity(),
        "retriever_k": 4,
        "vector_store": "FAISS",
        "index_path": "faiss_index",
        "fastapi_base_url": api_base_url,
    }

    request_contract = {
        "query": "What are the main improvements in GPT-4?"
    }

    response_contract = {
        "result": "Answer generated by the LLM with retrieved context.",
        "source_documents": [
            {
                "metadata": {
                    "source": "data/example.pdf"
                },
                "page_content": "Retrieved chunk text..."
            }
        ]
    }

    with st.expander("RAG API exposed by this app", expanded=False):
        st.write("**FastAPI exposure**")
        st.code(
            "uvicorn openai_compatible_api:app --host 0.0.0.0 --port 8000",
            language="bash",
        )
        st.write("**Base URL:**", api_base_url)
        st.write("**FastAPI endpoints (OpenAI-compatible)**")
        st.code(
            "GET /health\nGET /v1/models\nPOST /v1/chat/completions",
            language="text",
        )

        st.write("**Invocation method:** `qa_chain({\"query\": ...})`")
        st.write("**Request contract**")
        st.code(json.dumps(request_contract, indent=2), language="json")
        st.write("**Response contract**")
        st.code(json.dumps(response_contract, indent=2), language="json")
        st.write("**Current runtime configuration**")
        st.json(runtime)

st.title("Ask me anything about OpenAI Research")
_render_rag_api_panel()
query = st.text_input("Ask a question...")

if query:
    qa_chain = create_rag_chain()
    response = qa_chain({"query": query})
    st.write("**Answer:**", response["result"])

    source_documents = response.get("source_documents", [])
    source_files = _extract_source_files(source_documents)

    if source_files:
        file_counts = Counter(source_files)
        top_source_file, top_count = file_counts.most_common(1)[0]

        st.write("**Main source file used by RAG:**", os.path.basename(top_source_file))
        st.caption(f"Selected in {top_count} retrieved chunk(s)")

        with st.expander("Show retrieved source files"):
            for file_path, count in file_counts.most_common():
                st.write(f"- {os.path.basename(file_path)} ({count} chunk(s))")
    else:
        st.caption("No source file metadata found in retrieved documents.")